#pragma once

static const char* const AddBitmap[] = {
    "48 36 4 1 ",
    "  c None",
    ". c black",
    "X c green",
    "o c #808080",
    "                                                ",
    "                                                ",
    "                                                ",
    "                                                ",
    "                   ..........                   ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "          ..........XXXXXXXX..........          ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          .XXXXXXXXXXXXXXXXXXXXXXXXXX.o         ",
    "          ..........XXXXXXXX..........o         ",
    "           oooooooo.XXXXXXXX.oooooooooo         ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   .XXXXXXXX.o                  ",
    "                   ..........o                  ",
    "                    oooooooooo                  ",
    "                                                ",
    "                                                ",
    "                                                "
};

static const char* const RemoveBitmap[] = {
    "48 36 4 1 ",
    "  c None",
    ". c black",
    "X c red",
    "o c #808080",
    "                                                ",
    "                                                ",
    "                                                ",
    "                                                ",
    "              .                 .               ",
    "             .X.               .X.              ",
    "            .XXX.             .XXX.             ",
    "           .XXXXX.           .XXXXX.            ",
    "          .XXXXXXX.         .XXXXXXX.           ",
    "           .XXXXXXX.       .XXXXXXX.o           ",
    "            .XXXXXXX.     .XXXXXXX.o            ",
    "             .XXXXXXX.   .XXXXXXX.o             ",
    "              .XXXXXXX. .XXXXXXX.o              ",
    "               .XXXXXXX.XXXXXXX.o               ",
    "                .XXXXXXXXXXXXX.o                ",
    "                 .XXXXXXXXXXX.o                 ",
    "                  .XXXXXXXXX.o                  ",
    "                   .XXXXXXX.o                   ",
    "                  .XXXXXXXXX.                   ",
    "                 .XXXXXXXXXXX.                  ",
    "                .XXXXXXXXXXXXX.                 ",
    "               .XXXXXXX.XXXXXXX.                ",
    "              .XXXXXXX.o.XXXXXXX.               ",
    "             .XXXXXXX.o  .XXXXXXX.              ",
    "            .XXXXXXX.o    .XXXXXXX.             ",
    "           .XXXXXXX.o      .XXXXXXX.            ",
    "          .XXXXXXX.o        .XXXXXXX.           ",
    "           .XXXXX.o          .XXXXX.o           ",
    "            .XXX.o            .XXX.o            ",
    "             .X.o              .X.o             ",
    "              .o                .o              ",
    "                                                ",
    "                                                ",
    "                                                ",
    "                                                ",
    "                                                "
};